
export const budgetCategories = [
  "01. ATK & Barang Cetakan",
  "02. BBM Mobil",
  "03. BBM Motor",
  "04. Peralatan & Perlengkapan Kebersihan",
  "05. Konsumsi Jamuan Tamu",
  "06. Konsumsi Santri & Asatidz",
  "07. Mukafaah Pengurus Pondok (W.M)",
  "08. Rekening Telepon Dan Internet",
  "09. Rekening Listrik",
  "10. Tol Dan Parkir",
  "11. Biaya Pajak Tanah",
  "12. Biaya Pajak Mobil",
  "13. Biaya Pajak Motor",
  "14. Konsumsi Rapat & Kajian",
  "15. Perkebunan",
  "16. Perawatan Kendaraan",
  "17. Biaya Administrasi Bank",
  "18. Biaya Lainnya",
  "19. Peralatan & Perlengkapan Pondok",
  "20. Perbaikan Gedung",
  "21. Perjalanan Dinas",
  "22. Tunjangan Hari Raya (THR)",
];
